spring:
  profiles: default
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug

mariadb:
  url: jdbc:mariadb://localhost:3306/primavera
  username: primavera
  password: primavera
  allows : local, dev, prod

---

spring:
  profiles: dev
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
logging:
  level:
    org.springframework: warn
    com.genius.primavera: warn