spring:
  profiles: default
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug

com:
  genius:
    primavera:
      username: primavera
      password: primavera
      url: jdbc:mariadb://localhost:3306/primavera
      tables: user, role
      params:
        keyword: genius
        page: 1
        sort: desc
      users:
        - id: 1
          email: genius
        - id: 2
          email: genius2

plantPlaces:
  api:
    url: http://www.plantplaces.com
---

spring:
  profiles: dev
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
logging:
  level:
    org.springframework: warn
    com.genius.primavera: warn

