server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
            uri: git@github.com:csj4032/config-repo.git
            search-paths: account, front, order, product