language: java

jdk:
  - oraclejdk13

branches:
  only:
    - master

script: "./gradlew clean build"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

env:
  global:
    - COVERALLS_REPO_TOKEN=zkuwfYF8m7tHeHe09w23Om2CrQJg4hOWU

after_success:
  - ./gradlew cobertura coveralls