language: java

jdk:
  - oraclejdk13

branches:
  only:
    - master

script: "./gradlew clean build"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

after_success:
  - ./gradlew jacocoTestReport cobertura coveralls