spring:
  application:
    name: Privamera
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: primavera
    password: primavera
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        globally_quoted_identifiers: true
        jdbc:
          fetch_size: 30
          batch_size: 30
    open-in-view: false
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  devtools:
    livereload:
      enabled: true
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

logging:
  config: classpath:logback.xml