spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: study
    password: study
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
