spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera
    username: primavera
    password: primavera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt

com:
  genius:
    primavera:
      username: primavera
      password: primavera
      url: jdbc:genius://localhost/primavera
      tables:
        - user
        - role
      params:
        keyword: genius
        page: 1
        sort: desc
      users:
        - id: 1
          name: genius
        - id: 2
          name: genius2