spring:
  application:
    name: externalGateWay
  profiles:
    active: local
    include:
    - HystrixAndFeign

eureka:
  client:
    enabled: false

primavera:
  api:
    url: https://localhost:8443