spring:
  application:
    name: product
  cloud:
    config:
      uri: http://localhost:8888

server:
  tomcat:
    threads:
      max: 1
  port: 8083

logging:
  level:
    org.springframework: DEBUG