spring:
  application:
    name: Privamera

  banner:
    charset: UTF-8
    location: classpath:primavera.txt

mariadb:
  url: jdbc:mariadb://localhost:3306/primavera
  user: primavera
  password: primavera