spring:
  application:
    name: Privamera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug

mariadb:
  url: jdbc:mariadb://localhost:3306/primavera
  user: primavera
  password: primavera