spring:
  application:
    name: Privamera
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: primavera
    password: primavera
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        globally_quoted_identifiers: true
        jdbc:
          fetch_size: 30
          batch_size: 30
    open-in-view: false
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  devtools:
    livereload:
      enabled: true
  aop:
    proxy-target-class: false
    auto: false
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

server:
  port: 8080
#  ssl:
#    key-store: "classpath:keys/primavera.p12"
#    key-store-password: primavera
#    key-store-type: PKCS12
#    key-alias: primavera
#    protocol: TLS

logging:
  config: classpath:logback.xml

primavera:
  config:
    name: primavera
    enabled: true

sentry:
  dns: https://4084f8500752461897ebbfe3a067d36c@sentry.io/5166811
  environment: prodution
  servername: chap15
  release: 0.0.1-SNAPSHOT