spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: primavera
    password: primavera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback.xml

server:
  port: 8080

sentry:
  dns: https://4084f8500752461897ebbfe3a067d36c@sentry.io/5166811
  environment: local
  servername: chap15
  release: 0.0.1-SNAPSHOT