spring:
  datasource:
    username: primavera
    password: primavera
    url: jdbc:mariadb://localhost/primavera

logging:
  config: classpath:logback.xml

com:
  genius:
    primavera:
      username: primavera
      password: primavera
      url: jdbc:genius://localhost/primavera
      tables:
        - user
        - role
      params:
        keyword: genius
        page: 1
        sort: desc
      users:
        - id: 1
          name: genius
        - id: 2
          name: genius2