spring:
  application:
    name: Privamera

  banner:
    charset: UTF-8
    location: classpath:primavera.txt

mybatis:
  type-aliases-package: com.genius.primavera.domain.model
  type-handlers-package: com.genius.primavera.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

mariadb:
  url: jdbc:mariadb://localhost:3306/study
  user: study
  password: study