spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: primavera
    password: primavera

logging:
  level:
    org.springframework: debug
    com.genius.primavera: debug
