spring:
  application:
    name: Privamera
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/primavera
    username: primavera
    password: primavera
  banner:
    charset: UTF-8
    location: classpath:primavera.txt
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

google:
  client:
    clientId: ${OAUTH2_GOOGLE_CLIENTID}
    clientSecret: ${OAUTH2_GOOGLE_CLIENTSECRET}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30
  type-aliases-package: com.genius.primavera.domain
  type-handlers-package: com.genius.primavera.domain

logging:
  config: classpath:logback.xml

server:
  ssl:
    key-alias: primavera
    key-password: primavera
    key-store: chap09/primavera.jks
    key-store-type: PKCS12
  port: 8443