spring:
  application:
    name: front
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8080
  tomcat:
    max-threads: 10
    max-connections: 10
    connection-timeout: 1000

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org.springframework: debug
